config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Define root path
  root "orders#index"  # This will set the root path to the orders index page

  post '/orders/submit', to: 'orders#submit'
  resources :orders do
    member do
      get :success
      get :error
    end

    collection do
      get :phone_pe_redirect
      post :phone_pe_redirect
  end
  end

  post 'orders/paypal/create_payment'  => 'orders#paypal_create_payment', as: :paypal_create_payment
  post 'orders/paypal/execute_payment'  => 'orders#paypal_execute_payment', as: :paypal_execute_payment

  post 'orders/paypal/create_subscription'  => 'orders#paypal_create_subscription', as: :paypal_create_subscription
  post 'orders/paypal/execute_subscription'  => 'orders#paypal_execute_subscription', as: :paypal_execute_subscription
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 0, failed: 1, paid: 2, paypal_executed: 3}
  enum payment_gateway: { stripe: 0, paypal: 1, phonepe: 2 }
  belongs_to :product
  belongs_to :user

  scope :recently_created, ->  { where(created_at: 4.minutes.ago..DateTime.now) }

  def set_paid
    self.status = Order.statuses[:paid]
  end
  def set_failed
    self.status = Order.statuses[:failed]
  end
  def set_paypal_executed
    self.status = Order.statuses[:paypal_executed]
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  monetize :price_cents
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :prepare_new_order, only: [:paypal_create_payment, :paypal_create_subscription]

  def index
    products = Product.all
    @products_purchase = products.where(stripe_plan_name:nil, paypal_plan_name:nil)
    @products_subscription = products - @products_purchase
  end

  def submit
    @order = nil
    #Check which type of order it is

    if order_params[:payment_gateway] == "stripe"
      prepare_new_order

      Orders::Stripe.execute(order: @order, user: current_user)
    elsif order_params[:payment_gateway] == "paypal"
      @order = Orders::Paypal.finish(order_params[:charge_id])
    elsif order_params[:payment_gateway] == "phonepe"
      prepare_new_order
      @order&.save
      result = Orders::Phonepe.initiate_payment(order: @order, callback_url: success_order_path(id: @order.id))
    end
  ensure
    save_order_and_redirect
  end

  def paypal_create_payment
    result = Orders::Paypal.create_payment(order: @order, product: @product)
    if result
      render json: { token: result }, status: :ok
    else
      flash[:popup_message] = "Something went wrong while creating Payment"
      render json: {error: FAILURE_MESSAGE}, status: :unprocessable_entity
    end
  end

  def paypal_execute_payment
    if Orders::Paypal.execute_payment(payment_id: params[:paymentID], payer_id: params[:payerID])
      render json: {}, status: :ok
    else
      flash[:popup_message] = "Something went wrong while Executing Payment"
      render json: {error: FAILURE_MESSAGE}, status: :unprocessable_entity
    end
  end

  def paypal_create_subscription
    result = Orders::Paypal.create_subscription(order: @order, product: @product)

    if result
      render json: { token: result }, status: :ok
    else
      flash[:popup_message] = "Something went wrong while creating Subscription"
      render json: {error: FAILURE_MESSAGE}, status: :unprocessable_entity
    end
  end

  def paypal_execute_subscription
    result = Orders::Paypal.execute_subscription(token: params[:subscriptionToken])
    if result
      render json: { id: result}, status: :ok
    else
      flash[:popup_message] = "Something went wrong while Executing Subscription"
      render json: {error: FAILURE_MESSAGE}, status: :unprocessable_entity
    end
  end

  def success
    fetch_order_details
  end

  def error
    fetch_order_details
  end

  def phone_pe_redirect
    order = Order.find(params[:order_id])
    response = Orders::Phonepe.transaction_status(order: order)
    # Handle the response
    if response.is_a?(Net::HTTPSuccess)
      res = JSON.parse(response.body)
      if res['success'] == true && res['code'] == "PAYMENT_SUCCESS"
        if order.paid!
          flash[:popup_message] = "Your order was successfully placed!"
          redirect_to success_order_path(id: order.id)
        end
      end
    else
      flash[:popup_message] = order.error_message
      redirect_to error_order_path(id: order.id)
    end
  end

  private
  # Initialize a new order and and set its user, product and price.
  def fetch_order_details
    @order = Order.find(params[:id])
    @status = @order.status
  end

  def prepare_new_order
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @product = Product.find(@order.product_id)
    @order.price_cents = @product.price_cents
  end

  def save_order_and_redirect
    if @order&.save
      
      if @order.paid?
        flash[:popup_message] = "Your order was successfully placed!"
        redirect_to success_order_path(id: @order.id)
      elsif @order.failed? && !@order.error_message.blank?
        flash[:popup_message] = @order.error_message
        redirect_to error_order_path(id: @order.id)
      end
    else
      flash[:popup_message] = "Something went wrong. Please try again."
      redirect_to root_path
    end
  end

  def order_params
    params.require(:orders).permit(:product_id, :token, :payment_gateway, :charge_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GalaxyStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'popup', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="popup" class="popup hidden" data-popup-message="<%= flash[:popup_message] %>"></div>

    <%= yield %>
  </body>
</html>

app/views/orders/error.html.erb
<h1>Oops! Something Went Wrong</h1>
<p><%= @order.error_message %></p>
<p>Your order status is <b><%= @status %></b> </p>
<p>Please try again or contact support.</p>

app/views/orders/index.html.erb
<script src="https://www.paypal.com/sdk/js?client-id=<%= ENV['PAYPAL_CLIENT_ID'] %>"></script>
<%= stripe_javascript_tag %>

<div>
    <h1>List of products</h1>
    <%= form_tag({ controller: "orders", action: "submit" }, id: 'order-details') do %>
      <input id="order-type" type="hidden" value="stripe" name="orders[payment_gateway]">
      
      <div class="form_row">
        <h4>Charges/Payments</h4>
        <% @products_purchase.each do |product| %>
          <div data-charges-and-payments-section="true">
            <%= radio_button_tag 'orders[product_id]', product.id, @products_purchase.first == product %>
            <span id="radioButtonName<%= product.id %>"><%= product.name %></span>
            <span id="radioButtonPrice<%= product.id %>" data-price="<%= product.price_cents %>"><%= humanized_money_with_symbol(product.price) %></span>
          </div>
          <br>
        <% end %>
        
        <h4>Subscriptions</h4>
        <% @products_subscription.each do |product| %>
          <div>
            <%= radio_button_tag 'orders[product_id]', product.id, false %>
            <span id="radioButtonName<%= product.id %>"><%= product.name %></span>
            <span id="radioButtonPrice<%= product.id %>" data-price="<%= product.price_cents %>"><%= humanized_money_with_symbol(product.price) %></span>
          </div>
          <br>
        <% end %>
      </div>
      
      <hr>
      
      <h1>Payment Method</h1>
      <div class="form_row">
        <div>
          <%= radio_button_tag 'payment-selection', 'stripe', true, onclick: "changeTab();" %>
          <span>Stripe</span>
        </div>
        <br>
        <div>
          <%= radio_button_tag 'payment-selection', 'paypal', false, onclick: "changeTab();" %>
          <span>PayPal</span>
        </div>
        <br>
        <div>
          <%= radio_button_tag 'payment-selection', 'phonepe', false, onclick: "changeTab();" %>
          <span>PhonePe</span>
        </div>
        <br><br>
        
        <div id="tab-stripe" class="paymentSelectionTab active">
          <div id="card-element"></div>
          <div id="card-errors" role="alert"></div>
          <br><br>
          <%= submit_tag "Buy it!", id: "submit-stripe" %>
        </div>
        
        <div id="tab-paypal" class="paymentSelectionTab">
          <div id="submit-paypal"></div>
        </div>

        <div id="tab-phonepe" class="paymentSelectionTab">
          <button type="button" id="submit-phonepe" class="btn btn-primary">Pay with PhonePe</button>
        </div>  
        <br><br>
      </div>
      <hr>
    <% end %>
    
  <script>
    function changeTab() {
      var newActiveTabID = $('input[name="payment-selection"]:checked').val();
      $('.paymentSelectionTab').removeClass('active');
      $('#tab-' + newActiveTabID).addClass('active');
    }

    (function setupStripe() {
      // Initialize stripe with publishable key
      var stripe = Stripe("<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>");

      // Create Stripe credit card elements
      var elements = stripe.elements();
      var card = elements.create('card');

      // Add a listener in order to check if the div card-errors contains error details if any
      card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        document.getElementById('submit-stripe').disabled = false;
        if (event.error) {
          displayError.textContent = event.error.message;
        } else {
          displayError.textContent = '';
        }
      });

      // Mount Stripe card element in the #card-element div
      card.mount('#card-element');

      var form = document.getElementById('order-details');
      form.addEventListener('submit', function(event) {
        $('#submit-stripe').prop('disabled', true);
        event.preventDefault();
        stripe.createToken(card).then(function(result) {
          if (result.error) {
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
          } else {
            var $form = $("#order-details");
            $form.append($('<input type="hidden" name="orders[token]"/>').val(result.token.id));
            $('#order-type').val('stripe');
            $form.submit();
          }
        });
        return false;
      });
    }());

    (function setupPaypal() {
      function isPayment() {
        return $('[data-charges-and-payments-section] input[name="orders[product_id]"]:checked').length;
      }

      function submitOrderPaypal(chargeID) {
        var $form = $("#order-details");
        $form.append($('<input type="hidden" name="orders[charge_id]"/>').val(chargeID));
        $('#order-type').val('paypal');
        $form.submit();
      }

      paypal.Buttons({
        env: "<%= ENV['PAYPAL_ENV'] %>",
        createOrder: function() {
          $('#order-type').val("paypal");
          if (isPayment()) {
            return $.post("<%= paypal_create_payment_url %>", $('#order-details').serialize()).then(function(data) {
              return data.token;
            });
          } else {
            return $.post("<%= paypal_create_subscription_url %>", $('#order-details').serialize()).then(function(data) {
              return data.token;
            });
          }
        },
        onApprove: function(data) {
          if (isPayment()) {
            return $.post("<%= paypal_execute_payment_url %>", {
              paymentID: data.paymentID,
              payerID:   data.payerID
            }).then(function() {
              submitOrderPaypal(data.paymentID)
            });
          } else {
            return $.post("<%= paypal_execute_subscription_url %>", {
              subscriptionToken: data.orderID
            }).then(function(executeData) {
              submitOrderPaypal(executeData.id)
            });
          }
        }
      }).render('#submit-paypal');
    }());

    (function setupPhonePe() {
      document.getElementById('submit-phonepe').addEventListener('click', function () {
        var $form = $("#order-details");
        $('#order-type').val('phonepe');
        $form.submit();
      });
    })();
  </script>

  <style>
    #card-element {
      width:500px;
    }
    .paymentSelectionTab {
      display: none;
    }
    .paymentSelectionTab.active {
      display: block !important;
    }
  </style>

app/views/orders/success.html.erb
<% if @order&.id.present? && @order.id > 0 %>
  <h1>Thank You for Your Order!</h1>
  <p>Your order ID is <b><%= @order.id %></b></p>
  <p>Your order status is <b><%= @status %></b></p>
  <p>We appreciate your business.</p>
<% else %>
 <h1>Thank You for Your Order!</h1>
 <p>Your Payment for you'r favourate with PhonePe is Successfull.</p>
<% end %>